### ISSUE TITLE
Linking means after Bhattacharya´s method

### ISSUE THREAD

**Issue by ppagliosa** [tokami/TropFishR#16]
Dear Tobias Mildenberger,
Thanks a lot for the TropFishR package!!!
I am new with TropFishR. 
I appreciate if you could indicate which function I should use to run the "linking of means (to represent the same cohort ) after Bhattacharya's method using lenght frequency data".

**Comment by tokami** [comment]
Hi ppagliosa,
Thank you for your interest in TropFishR. Did I understand you correctly that you want to use the results of Bhattacharya's method (mean length per cohorts) to estimate growth parameters (K and Linf)? If so, you can use the function `growth_tagging`. Just create a new data frame based on the results form Bhattacharya and feed them into `growth_tagging`. For the example data set `synLFQ1`, this could look something like this:

```
res_Bh = Bhattacharya(synLFQ1) # choose following points: 2-8, 12-17, 19-23, 26-30

mydat =  data.frame(L1 = res_Bh$Lmean_SD_list[1:3,2], 
                     L2 = res_Bh$Lmean_SD_list[2:4,2], 
                     delta_t = c(1,1,1))

growth_tagging(method = "Munro", param = mydat, Linf_range = c(45,55), time_unit = "year")
```

Please note, this code assumes that you followed the example described in `help(Bhattacharya)` and that you assume that the time interval (age difference) between the cohorts is 1 year. You can find more information on this in "Introduction to tropical fish stock assessment" by Sparre & Venema (1998) page 88.

I hope this helps! 
Kind regards,
Tobias
