### ISSUE TITLE
catchCurve

### ISSUE THREAD

**Issue by ppagliosa** [tokami/TropFishR#17]
Dear Tobias Mildenberger,
I am having some trobles running "catchCurve" function. I modified my length-frequency data with the "lfqModify" function and, after run catchCurve the programm returns the following message:"Error: "x" must be numeric.". In fact the same message return when I run the examples contained in the help of the catchCurve function. It is maybe possible that the function is not working properly? I thank you in advance.

**Comment by marchtaylor** [comment]
@ppagliosa - without a reproducible example, debugging your issue will be difficult. I just ran the examples and all seem to run correctly. I assume that you selected via mouse-clicks your end points for the regression?

**Comment by ppagliosa** [comment]
Hi, I am trying:

> data(goatfish)
> catchCurve(goatfish)
Error: 'x' must be numeric.

**Comment by marchtaylor** [comment]
This works for me. Have you tried reinstalling? `devtools::install_github(“tokami/TropFishR”)`

**Comment by ppagliosa** [comment]
Hi, I think I discovered what is wrong.  
When I load only "TropfishR" the script (and examples) works fine. 
When I load "TropfishR" and "FSA" packages the error happened. I think this happens because the two packages have a function named "catchCurve", but they use different objects to run. Seems like when the two packages were loaded the "FSA" catchCurve function surpass the catchCurve function of the "TropfishR". Anyway, thank you for the help.

**Comment by marchtaylor** [comment]
OK, glad you solved the issue. If you have a conflict, you can use `TropFishR::catchCurve()` to call the correct function.

**Comment by ppagliosa** [comment]
great. Thanks!!!
