### ISSUE TITLE
Error in lfqModify command, with the argument 'vectorise_catch'

### ISSUE THREAD

**Issue by mohammad4458** [tokami/TropFishR#18]
Hi
Thanks for TropFishR package
I have problem with `lfqModify `
each time running the code `lfq_sum <- lfqModify(synLFQ4, vectorise_catch = TRUE)` this errors will display:
```
Error in lfqModify(synLFQ4, vectorise_catch = TRUE) : 
  unused argument (vectorise_catch = TRUE)
```
How I can fix this issue?
Thanks in advance
Mohammad

`

**Comment by marchtaylor** [comment]
Hi Mohammad,
Is it possible you are using an old version of the package? `lfqModify` did not originally have the argument `vectorise_catch` - only in versions post March 1st.

try an update of the most recent version: `devtools::install_github(“tokami/TropFishR”)`

**Comment by mohammad4458** [comment]
Thanks for reply
Is there any comment for vectorizing catch matrix in new version?

**Comment by marchtaylor** [comment]
Yes, there is. Your​example works for me with the new version. Just reinstall and try again.

**Comment by mohammad4458** [comment]
Thanks a lot
