### ISSUE TITLE
ideas for improvement

### ISSUE THREAD

**Issue by tokami** [tokami/TropFishR#2]
- option for variable size class intervals within functions or separate function which rearranges datasets
- separate functions which create classes as input for functions? e.g. lfq in fisat...
- output of functions should be class which can be used for plot function, create by class(argument) = "name of class"
- separate plot functions, automatically using output classes of functions: output = class("VPA") plot(output) -> desired graph depending on class
- plot option within function: plot = T or F

**Comment by marchtaylor** [comment]
some code formatting suggestions. I recommend not using the level name "Dataframe" in the results output of functions (e.g. Line 209 of VPA), so as not to confuse. Also, dont abbreviate "T" and "F" for TRUE and FALSE. If these are ever defined by a user, then the functions won't work correctly.

**Comment by tokami** [comment]
add production model by Palle & Tomlinsson 1969 ?

**Comment by tokami** [comment]
add depletion models ?

**Comment by tokami** [comment]
add function to correct length-frequency data using selection curves

**Comment by tokami** [comment]
add format field in description of functions, describing the output of the function?

**Comment by tokami** [comment]
develop example dataset for length at first capture data and develop the calculation steps for Z_BevertonHolt.R, still pending

**Comment by tokami** [comment]
add stock recruitment relationship

**Comment by tokami** [comment]
add selection ogive option to `predict_mod(type = 'ypr')`
