### ISSUE TITLE
ypr function

### ISSUE THREAD

**Issue by Isabella84** [tokami/TropFishR#21]
Dear developer,
I have problem in run the command ypr. I am using the following code:

devtools::install_github("tokami/TropFishR")
require(TropFishR)
Winf=(0.000006*30)^3.085
m=mean(as.vector(c(0.755,	0.567,	0.483)))
param=list(Linf=30,Winf=Winf,K=0.24,t0=-0.61,M=m,tr=0.25,tc=0.5)

#param a list consisting of following parameters (not all are required):
#• Linf: infinite length in cm,
#• Winf: infinite weight,
#• K: growth coefficent for investigated species per year [1/year],
#• t0: theoretical time zero, at which individuals of this species hatch,
#• M: natural mortality,
#• tr: age of recruitment,
#• tc: age of first capture;
#FM_change vector with ascending fishing mortalities,
#t default NA

ypr(param, FM_change=seq(0,2,0.1))

Thank you in advance for your help,
Isabella

**Comment by lidach** [comment]
Sorry I'm not the developer, but you can use this code instead for ypr:
output <- predict_mod(param, type = "ypr",
                      FM_change = seq(0,3,0.1), 
                      hide.progressbar = TRUE, plot = TRUE)

**Comment by Isabella84** [comment]
Thank you very much for your help.

Isabella


________________________________
Da: lidach <notifications@github.com>
Inviato: giovedì 9 novembre 2017 08:58
A: tokami/TropFishR
Cc: Isabella Bitetto; Author
Oggetto: Re: [tokami/TropFishR] ypr function (#21)


Sorry I'm not the developer, but you can use this code instead for ypr:
output <- predict_mod(param, type = "ypr",
FM_change = seq(0,3,0.1),
hide.progressbar = TRUE, plot = TRUE)

**Comment by tokami** [comment]
Thank you @lidach for helping out! Let us know if there is any other problem, @Isabella84 , otherwise I close this issue.
