### ISSUE TITLE
catcurve calc_ogive

### ISSUE THREAD

**Issue by latifapelage** [tokami/TropFishR#25]
Hello! I can't run the example because after clicking in the 2 points of the curve I have an error message.
output <-catchCurve(synLFQ3, calc_ogive = TRUE)
Please choose the minimum and maximum point in the graph 
to include for the regression line!
Error in xy.coords(x, y) : 'x' and 'y' lengths differ
In addition: Warning messages:
1: In if (I == which(ind)) { :
  the condition has length > 1 and only the first element will be used
2: In min(x) : no non-missing arguments to min; returning Inf
3: In max(x) : no non-missing arguments to max; returning -Inf
Thank you in advance for your response!

**Comment by tokami** [comment]
Hi @latifapelage,

thank you for your comment. Do you have a minimal example to reproduce your error?

**Comment by tokami** [comment]
the catch curve with this data sets works for me. I think your error is just due to the points you have chosen. Try:

```
opar <- par(mfrow=c(2,1))
res <- catchCurve(synLFQ3, calc_ogive = TRUE, reg_int = c(9,21))
par(opar)
```
