### ISSUE TITLE
Development version not installing 

### ISSUE THREAD

**Issue by Saheen0350** [tokami/TropFishR#29]
> install.packages(devtools)
Error in install.packages : object 'devtools' not found
> devtools::install_github(“tokami/TropFishR”)
Error: unexpected input in "devtools::install_github(“"

**Comment by marchtaylor** [comment]
Might this be an issue with your "smart" quotation marks. I don't see the issue right away.

**Comment by alko989** [comment]
devtools should be in quotes. And use normal double quotes ", instead of the fancy ones “

`install.packages("devtools")`

Also you can use the lighter "remotes" package.

```
install.packages("remotes")
remotes::install_github("tokami/TropFishR")
```
 
These were wrong in the Readme.md file. I made changes and sent a pull request to fix those.
