### ISSUE TITLE
One cohort analysis

### ISSUE THREAD

**Issue by freddycus** [tokami/TropFishR#30]
I am trying to apply the ELEFAN routine to jellyfish, their lifespan oscilates typically from 1 to 4 months making it hard to differenciate between cohorts as some of them might be spaced just for 15 days instead of a whole year. However, for one of the species I am completely sure that for the whole lifespan I only have 1 cohort but when I throw the analysis I receive a ncohort of 4, being it extremely high given the loleny recruitment peak registered for the data. Is it possible to fix the ncohort before running ELEFAN so I can get a K value more consistent with the input data?

**Comment by marchtaylor** [comment]
Hello,
Although I haven't used it for a long time, the `agemax` argument should fix the number of cohorts that are fit by ELEFAN (used internally by `lfqFitCurves`). That said, I don't think we ever envisioned it to be used in an absolute way - more as a way to standardize the value between fittings using different settings. Looking at the code for that function, it may round up to 2 cohorts when defining `agemax = 1`. Perhaps, `agemax = 0` would work in your case where they live less than a year. If you can give this a try with your data and get back to us, we would be most appreciative.

**Comment by freddycus** [comment]
Hello, Dr. Taylor.
Fixing the agemax = 1 or a fraction of year has been useful for the calculation with my data. 
In case someone find him/herself in the same situation I wouldn't recommend to use agemax=0 because it makes ELEFAN uncapable of providing with a suitable K value given that all of them obtain the same score.
Thanks a lot for your help
