### ISSUE TITLE
VBGF add na.rm=F default

### ISSUE THREAD

**Issue by SimonDedman** [tokami/TropFishR#32]
Dear Tobias,

Do you think it would be possible to add a na.rm parameter to VBGF, defaulting to FALSE like max() does (for example)? This would avoid having to code VBGF calls in an if/else wrapper to deal with NAs when running VBGF on a vector with NAs.

Thanks!

**Comment by tokami** [comment]
Thank you for the good idea! 
The `na.rm` option is implemented in the 'nojags' branch. Please install with `remotes::install_github("tokami/TropFishR", ref="nojags")`.
