### ISSUE TITLE
Error: Failed to install 'TropFishR' from GitHub:

### ISSUE THREAD

**Issue by xiphiasTR** [tokami/TropFishR#34]
Hi all,
I have been trying to use TropfishR package In fact, I got the same message below.
![Screen Shot 2020-07-03 at 15 32 32](https://user-images.githubusercontent.com/60401276/86469622-6f3d4900-bd42-11ea-8fcf-19ba0ef2f332.png)

Error: package or namespace load failed for ‘TropFishR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so, 6): Library not loaded: /usr/local/gfortran/lib/libgomp.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so
  Reason: image not found

If you have an idea to fix it and use package, I would be great
Best regards,
Tevfik 

edit: Ps : R version 4.0.0 Patched (2020-05-03 r78349) -- "Arbor Day"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

**Comment by tokami** [comment]
Please make sure that Xcode (https://apps.apple.com/us/app/xcode/id497799835?mt=12) is installed and try again.

**Comment by tokami** [comment]
(Make sure to also install Command line tools). Find more information here: https://support.rstudio.com/hc/en-us/articles/200486498-Package-Development-Prerequisites
