### ISSUE TITLE
Error: Failed to install 'TropFishR' from GitHub

### ISSUE THREAD

**Issue by Ibrahim05-05** [tokami/TropFishR#35]
Hi, I'm using Mac device and I was unable to install 'TropFishR' from GitHub and some errors appeared as below:

Installing 23 packages: rlang, digest, backports, diffobj, waldo, ps, callr, brio, cli, R6, labeling, testthat, tibble, xfun, htmlwidgets, sandwich, iterators, data.table, Formula, foreach, ff, RcppArmadillo, doParallel
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/rlang_0.4.8.tgz'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  (converted from warning) URL 'https://cran.rstudio.com/bin/macosx/contrib/4.0/rlang_0.4.8.tgz': status was 'SSL connect error'
Error: Failed to install 'TropFishR' from GitHub:
  (converted from warning) download of package ‘rlang’ failed
> library(TropFishR)
Error: package or namespace load failed for ‘TropFishR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so, 6): Library not loaded: /usr/local/gfortran/lib/libgomp.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/library/gmm/libs/gmm.so
  Reason: image not found
In addition: Warning message:
package ‘TropFishR’ was built under R version 4.0.2 

Note that I'm using  ''R'' version 4.0.1 (2020-06-06) -- 
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit).

would you please help to solve the issues with Mac device. 

Thank you.

**Comment by tokami** [comment]
Please make sure that Xcode (https://apps.apple.com/us/app/xcode/id497799835?mt=12) is installed and try again.

**Comment by tokami** [comment]
(Make sure to also install Command line tools). Find more information here: https://support.rstudio.com/hc/en-us/articles/200486498-Package-Development-Prerequisites
