### ISSUE TITLE
problem with ELEFAN score_mat in version1.6.2

### ISSUE THREAD

**Issue by paudelabarra** [tokami/TropFishR#36]
Hi,

I am trying to run the tutorial "Single-species fish stock assessment with TropFishR" with version 1.6.2. ELEFAN function is not returning score_mat. This is how it looks like

```
res_RSA <- ELEFAN(synLFQ7a, Linf_range = seq(119,139,1), MA = 5,
                   K_range = seq(0.01,2,0.1), addl.sqrt = TRUE,
                   hide.progressbar = TRUE, contour=5)

# find 3 highest score values
n <- length(res_RSA$score_mat)
n
```
I get:
[1] 0

Later ,I installed version 1.2 from CRAN archive and got everything to work fine. Do you know why this may be?

Thanks!

**Comment by tokami** [comment]
We used to return the `score_mat` in older versions of TropFishR and due to some reasons it got lost in one of the version updates. This is now corrected.
