### ISSUE TITLE
Bug in Z_CPUE

### ISSUE THREAD

**Issue by tokami** [tokami/TropFishR#37]
noted by Hadi:

- remove CPUE[4] <- sum(CPUE[4:length(CPUE)]) in Heincke and Chapman method
- replace sum_CPUE.H.n <- sum(CPUE[2:length(CPUE)]) with sum_CPUE.H.n <- sum(CPUE[2:length(CPUE)] * 1:(length(CPUE)-1))

**Comment by havuviet** [comment]
Dear All,

When I install package “TropFishR”, the errors are as below, could anyone help me to solve it.
Many thanks

Vu Viet Ha
—


> install.packages("TropFishR")
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.1/TropFishR_1.6.2.tgz'
Content type 'application/x-gzip' length 1751795 bytes (1.7 MB)
==================================================
downloaded 1.7 MB


The downloaded binary packages are in
	/var/folders/8s/c8rnm4qx40v5qd80vgzpml5c0000gp/T//RtmpJmwWcK/downloaded_packages
> library(TropFishR)
Error: package or namespace load failed for ‘TropFishR’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/4.1/Resources/library/gmm/libs/gmm.so':
  dlopen(/Library/Frameworks/R.framework/Versions/4.1/Resources/library/gmm/libs/gmm.so, 6): Library not loaded: /usr/local/gfortran/lib/libgomp.1.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/4.1/Resources/library/gmm/libs/gmm.so
  Reason: image not found

**Comment by tokami** [comment]
Dear @havuviet,

I assume you have a macintosh? Please install Xcode and try again!

Hope this helps,
Tobias

**Comment by havuviet** [comment]
Hi,

I have installed Xcod then run Rstudio, however the errors are still not solved. Please continous to advice me to solve these errors,
Many thanks,

**Comment by tokami** [comment]
Do you have these developer tools installed? https://cran.r-project.org/bin/macosx/tools/

If you have Xcode and all of these tools installed and still get the same messages, then you might need to manually create a link, see e.g. https://stackoverflow.com/questions/57207357/dyld-library-not-loaded-usr-local-gfortran-lib-libgfortran-3-dylib-reason-im
